version: 1
formatters:
  simple:
    format: '[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    level: DEBUG
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    mode: a
    filename: ../logs/webapp.log
    maxBytes: 1048576
    backupCount: 5

loggers:
  simpleExample:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]

